/** Contenus adaptés de la plaquette EPUREAU fournie, pages 2 et 3. */
export const sectorMap = [
  {id:"btp",title:"BTP & infrastructures",short:"BTP",text:"Des solutions pour la potabilisation de l’eau et l’épuration des eaux usées domestiques de vos infrastructures.",points:"Études et conception des installations\nRéalisation des ouvrages\nSuivi et maintenance",href:"/ingenierie/notre-expertise",image:"/images/illustrations/ingenierie.webp",x:565,y:145},
  {id:"industries",title:"Industries",short:"Industries",text:"De l’eau de process au traitement des effluents, nous accompagnons les performances de vos installations et l’hygiène de vos lignes de production.",points:"Traitement des utilités : chaudières et refroidissement\nNettoyage CIP / COP et lavage des bouteilles\nLubrification des convoyeurs",href:"/service-aux-industries",image:"/images/illustrations/industrie.webp",x:945,y:265},
  {id:"hotellerie",title:"Hôtellerie & services",short:"Hôtellerie",text:"Une eau de qualité, des établissements propres et une gestion efficace des consommations au service de votre accueil.",points:"Qualité de l’eau\nHygiène des établissements et des cuisines\nAccompagnement des équipes",href:"/hygiene-institutionnelle",image:"/images/illustrations/hygiene.webp",x:745,y:340},
  {id:"hopitaux",title:"Établissements hospitaliers",short:"Hôpitaux",text:"Des solutions pour la qualité de l’eau, l’hygiène hospitalière et la gestion des effluents, dans le respect des exigences de votre établissement.",points:"Traitement de l’eau\nHygiène hospitalière\nGestion des effluents",href:"/hygiene-institutionnelle",image:"/images/gal-5.jpg",x:340,y:245},
  {id:"collectivites",title:"Collectivités & institutions",short:"Collectivités",text:"Nous accompagnons les projets publics de potabilisation, d’assainissement et d’hygiène, de l’étude au suivi des installations.",points:"Potabilisation de l’eau\nAssainissement et traitement des eaux usées\nAccompagnement des projets publics",href:"/ingenierie/notre-expertise",image:"/images/gal-4.jpg",x:230,y:405},
  {id:"buanderies",title:"Buanderies professionnelles",short:"Buanderies",text:"Des solutions pour l’hygiène du linge, le traitement de l’eau et l’optimisation des équipements de buanderie.",points:"Hygiène du linge\nTraitement de l’eau\nOptimisation des équipements",href:"/hygiene-institutionnelle",image:"/images/illustrations/hygiene.webp",x:550,y:530},
] as const;
export const brochureUrl="/brochures/epureau-plaquette.pdf";
