export const englishUi: Record<string,string> = {
 "Envoyer ma réclamation":"Send my complaint","Notre société":"Our company","Notre histoire et notre équipe":"Our history and team","Conception, réalisation, exploitation":"Design, construction and operation","Stations livrées en Côte d'Ivoire":"Plants delivered in Côte d’Ivoire",
 "Demander une cotation":"Request a quote","Ouvrir le menu":"Open menu","Notre expertise":"Our expertise","Nos réalisations":"Our projects","Service aux industries":"Industrial services","Services aux industries":"Industrial services","Hygiène institutionnelle":"Institutional hygiene","Produits":"Products","Produits NALCO":"NALCO products","Produits ECOLAB":"ECOLAB products","Commodités & réactifs":"Commodities & reagents","Carrière":"Careers","Mentions légales":"Legal notice","Confidentialité":"Privacy","Réclamation client":"Customer complaint","Formulaire de cotation":"Quotation form","Autres pages":"More pages","— Tous droits réservés":"— All rights reserved",
 "Ingénierie de l'eau":"Water engineering","Ingénierie du traitement de l’eau":"Water treatment engineering","À propos":"About us","Industries":"Industries","Médiathèque":"Media library","L’entreprise, nos valeurs, nos équipes":"Our company, values and team","Rejoindre notre équipe":"Join our team","Nos solutions de traitement":"Our treatment solutions","Stations & projets livrés":"Plants and completed projects","Parlons de votre projet":"Tell us about your project","Demande de cotation / information":"Quotation / information request","Signaler un problème":"Report a problem",
 "Experts en ingénierie du traitement de l'eau : conception et réalisation de stations, service aux industries, hygiène institutionnelle et négoce des produits NALCO et ECOLAB.":"Water treatment engineering specialists: plant design and construction, industrial services, institutional hygiene, and supply of NALCO and ECOLAB products.",
 "Demande de cotation ou d'information":"Request a quote or information","Décrivez-nous votre installation : nous revenons vers vous avec une proposition chiffrée.":"Tell us about your facility and we will get back to you with a quotation.","Nom et prénom *":"Full name *","Société / établissement *":"Company / organisation *","E-mail professionnel *":"Work email *","Téléphone":"Phone","Objet de la demande":"Subject","Votre besoin (effluent, débit, site, contraintes…) *":"Your requirements (effluent, flow rate, site, constraints…) *","— vous pouvez aussi nous écrire directement à":"— you can also email us directly at","Demande envoyée":"Request sent","Copie transmise à nos équipes et enregistrée dans le tableau de bord de suivi. Nous vous répondons sous 48 h ouvrées.":"Your request has been sent to our team and recorded for follow-up. We will respond within two working days.",
 "Votre demande concerne":"Your enquiry concerns","Choisir un domaine":"Choose a field","Produits chimiques":"Chemical products","Autre demande":"Other enquiry","Gamme de produits":"Product range","Choisir une gamme":"Choose a range","Nom et prénom":"Full name","Société / établissement":"Company / organisation","E-mail professionnel":"Work email","Téléphone (facultatif)":"Phone (optional)","Votre besoin":"Your requirements","Votre demande a été prise en compte. Notre équipe reviendra vers vous.":"Your request has been received. Our team will get back to you.","Vous pouvez aussi écrire à":"You can also email","Envoi en cours…":"Sending…","Envoyer ma demande":"Send my request","Envoi impossible":"Unable to send","Envoi impossible pour le moment.":"Unable to send at the moment.",
 "Décrivez brièvement votre demande.":"Briefly describe your enquiry.","Type d’installation, localisation, besoins et contraintes…":"Type of facility, location, requirements and constraints…","Activité du site, installations concernées et besoin d’accompagnement…":"Site activity, facilities involved and support required…","Type d’établissement, entretien du linge, locaux ou cuisines…":"Type of establishment, laundry, premises or kitchen cleaning…","Produits recherchés, conditionnement et quantités souhaitées…":"Products required, packaging and quantities…",
 "Votre vie privée":"Your privacy","Ce site ne dépose aucun cookie publicitaire. Seule une mesure de fréquentation interne est réalisée, sans cookie et sans conserver votre adresse IP. Aucune donnée n’est transmise à un service tiers, sauf si vous demandez vous-même l’affichage de la carte Google Maps sur la page contact.":"This site does not use advertising cookies. Internal audience measurement uses no cookies and does not retain your IP address. No data is sent to a third-party service unless you choose to display the Google Maps map on the contact page.","Fonctionnement du site":"Site functionality","Sécurité des formulaires et affichage. Nécessaires, toujours actifs.":"Form security, display and language preference. Required and always active.","Toujours actifs":"Always active","Mesure de fréquentation":"Audience measurement","Pages consultées, provenance et type d’appareil, de façon anonyme.":"Anonymous information about pages viewed, traffic sources and device types.","Enregistrer mes choix":"Save my choices","Tout accepter":"Accept all","Refuser":"Reject","Personnaliser":"Customise","Gérer les cookies":"Cookie preferences",
 "Notre établissement est référencé":"Our business is listed as","sur Google Maps. La carte est fournie par Google : en l’affichant, vous acceptez le dépôt de ses cookies.":"on Google Maps. The map is provided by Google: displaying it allows Google to set its cookies.","Afficher la carte":"Show map","Ouvrir dans Google Maps":"Open in Google Maps","Tous les albums":"All albums","Photo du chantier":"Project photo","Fermer la photo":"Close photo","Formulaire de réclamation client":"Customer complaint form","Votre réclamation":"Your complaint","Les champs marqués d’un astérisque sont obligatoires.":"Fields marked with an asterisk are required.","E-mail *":"Email *","Produit ou prestation concerné *":"Product or service concerned *","Sélectionner un domaine":"Choose a field","Facturation ou livraison":"Billing or delivery","Autre":"Other","Référence de commande, facture ou projet":"Order, invoice or project reference","Décrivez le problème rencontré *":"Describe the problem *","Quelle solution attendez-vous ?":"What solution would you like?","Site internet":"Website","Vos coordonnées et les informations fournies servent à traiter votre réclamation et à vous recontacter. Évitez de transmettre des données sensibles dans ce formulaire.":"We use your contact details and the information provided to handle your complaint and contact you. Please do not include sensitive data in this form.","Vous pouvez nous écrire à":"You can email us at",". Les informations saisies ont été conservées dans le formulaire.":". Your details have been kept in the form.","En savoir plus →":"Learn more →","Revenir en haut de la page":"Back to top","Voir le projet":"View project","Fermer":"Close","Application":"Application","Secteurs":"Sectors","Conditionnement":"Packaging","Aller au contenu":"Skip to content"
};
const key=(text:string)=>text.trim().replace(/\s+/g," ").replace(/[’‘]/g,"'");
const normalized=new Map(Object.entries(englishUi).map(([fr,en])=>[key(fr),en]));
export function uiText(text:string,language:"fr"|"en") {
 if(language!=="en")return text;
 const translated=normalized.get(key(text));
 return translated===undefined?text:(text.match(/^\s*/)?.[0]||"")+translated+(text.match(/\s*$/)?.[0]||"");
}
