"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { Identity } from "@/lib/auth";
import type { Entry } from "@/lib/admin-store";
import type { CustomerRequest } from "@/lib/admin-requests";
import type { ContentData, Document, PageDefinition } from "@/content/admin-types";
import { may } from "@/content/admin-access";
type Field={key:string;label:string;type?:string};
type Payload={data:unknown[];fields?:Field[];pages?:PageDefinition[];team?:{id:string;name:string}[]};
const sections:Record<string,string>={dashboard:"Vue d’ensemble",requests:"Demandes & réclamations",pages:"Pages du site",projects:"Réalisations",media:"Médiathèque",brochures:"Brochures",blog:"Blog",settings:"Paramètres",users:"Utilisateurs",audit:"Journal des accès"};
const labels:Record<string,string>={nouvelle:"Nouvelle",en_cours:"En cours",traitee:"Traitée"};
const roleNames:Record<string,string>={admin:"Administrateur",editeur:"Éditeur",commercial:"Commercial"};
async function request(url:string,body?:unknown){
 const result=await fetch(url,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});
 const json=await result.json();if(!result.ok)throw new Error(json.message||"Opération impossible.");return json;
}
export default function AdminConsole({user,initial,local}:{user:Identity;initial:Payload;local:boolean}){
 const [section,setSection]=useState("dashboard"),[payload,setPayload]=useState(initial),[selected,setSelected]=useState<Entry<Document>|null>(null);
 const [loading,setLoading]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[month,setMonth]=useState(""),[dirty,setDirty]=useState(false);
 async function open(next:string,saved=false){
  if(dirty&&!saved&&!confirm("Quitter sans enregistrer vos modifications ?"))return;
  setLoading(true);setError("");setDirty(false);setSelected(null);setSearch("");
  try{const data=await request("/api/admin/content?section="+next);setPayload(data);setSection(next);}catch(e){setError((e as Error).message);}finally{setLoading(false);}
 }
 const requests=(section==="dashboard"||section==="requests"?payload.data:[]) as Entry<CustomerRequest>[];
 const filtered=requests.filter(({value:r})=>(!status||r.statut===status)&&(!month||r.cree_le.startsWith(month))&&[r.nom,r.societe,r.objet,r.email,r.besoin].join(" ").toLowerCase().includes(search.toLowerCase()));
 const rows=payload.data as Entry<Document>[];
 function choose(row:Entry<Document>){if(dirty&&!confirm("Quitter sans enregistrer vos modifications ?"))return;setSelected(row);setDirty(false);}
 function create(){
  const key=section==="users"?"":crypto.randomUUID();
  choose({key,revision:0,updated:"",value:{title:"Nouveau contenu",draft:section==="media"?{type:"photo"}:{},published:null,order:rows.length}});
 }
 return <div className="admin-app">
  <aside className="admin-sidebar"><Link className="admin-brand" href="/"><img src="/images/logo.png" width="560" height="162" alt="EPUREAU Côte d’Ivoire" /></Link><span className="admin-caption">ESPACE ADMINISTRATION</span><nav aria-label="Administration">{Object.entries(sections).filter(([key])=>may(user.role,key)).map(([key,name],i)=><button type="button" key={key} aria-current={section===key?"page":undefined} onClick={()=>open(key)} disabled={loading}><span>{String(i+1).padStart(2,"0")}</span>{name}</button>)}</nav><div className="admin-account"><b>{user.name}</b><small>{roleNames[user.role]}</small><form action="/api/admin/login" method="post"><input type="hidden" name="_method" value="delete" /><button type="submit">Se déconnecter ↗</button></form></div></aside>
  <main className="admin-main"><header className="admin-top"><div><span className="admin-kicker">EPUREAU Côte d’Ivoire</span><h1>{sections[section]}</h1></div><a className="admin-button secondary" href="/" target="_blank" rel="noreferrer">Voir le site ↗</a></header>
   {local&&<p className="admin-local">Version locale · Les données sont conservées sur cet ordinateur. Aucune publication sur Internet.</p>}
   {error&&<p role="alert" className="admin-error">{error}</p>}
   {loading?<p role="status">Chargement…</p>:<>
   {section==="dashboard"&&<><div className="admin-welcome"><div><span>Bienvenue</span><h2>Votre site, à jour<br />et entre vos mains</h2><p>Modifiez vos contenus, préparez vos publications et suivez les demandes de vos clients.</p></div><div className="admin-watermark">E</div></div>{may(user.role,"requests")&&<><div className="admin-stats">{[["Ce mois",requests.filter(r=>r.value.cree_le.startsWith(new Date().toISOString().slice(0,7))).length],["À traiter",requests.filter(r=>r.value.statut==="nouvelle").length],["En cours",requests.filter(r=>r.value.statut==="en_cours").length],["Traitées",requests.filter(r=>r.value.statut==="traitee").length]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="admin-card"><h2>Dernières demandes</h2>{requests.length?requests.slice(0,5).map(r=><div className="admin-list-line" key={r.key}><div><b>{r.value.societe}</b><p>{r.value.objet}</p></div><span className={"admin-badge "+r.value.statut}>{labels[r.value.statut]}</span></div>):<p className="admin-empty">Les nouvelles cotations et réclamations apparaîtront ici.</p>}<button className="admin-button" onClick={()=>open("requests")}>Consulter les demandes</button></div></>}<div className="admin-quick">{["pages","projects","media"].filter(key=>may(user.role,key)).map(key=><button key={key} onClick={()=>open(key)}><span>{sections[key]}</span><b>Ouvrir →</b></button>)}</div></>}
   {section==="requests"&&<><div className="admin-filters"><label>Rechercher<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, société, objet…" /></label><label>Statut<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Mois<input type="month" value={month} onChange={e=>setMonth(e.target.value)} /></label><a className="admin-button secondary" href={"/api/admin/content?section=requests&format=csv&status="+status+"&month="+month}>Exporter CSV</a></div><p>{filtered.length} demande(s)</p><div className="admin-request-list">{filtered.map(row=><RequestCard key={row.key+row.revision} row={row} team={payload.team||[]} onSaved={()=>open("requests")} />)}{!filtered.length&&<div className="admin-card admin-empty">Aucune demande ne correspond à ces critères.</div>}</div></>}
   {section==="audit"&&<div className="admin-card">{(payload.data as Entry<{actor:string;action:string;date:string}>[]).map(r=><div className="admin-list-line" key={r.key}><div><b>{r.value.action}</b><p>{r.value.actor}</p></div><time>{new Date(r.value.date).toLocaleString("fr-FR")}</time></div>)}</div>}
   {!["dashboard","requests","audit"].includes(section)&&<>
    {section==="blog"&&<p className="admin-info">Le blog reste masqué tant que « Blog actif » n’est pas réglé sur « oui » dans les paramètres publiés.</p>}
    <div className="admin-content-grid"><div className="admin-content-list"><label className="admin-search">Rechercher<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un contenu" /></label>{!["pages","settings"].includes(section)&&<button className="admin-button" onClick={create}>+ {section==="users"?"Ajouter un compte":"Ajouter un contenu"}</button>}
    {rows.filter(r=>!r.value.deleted).filter(r=>(r.value.title||String((r.value as unknown as {name?:string}).name||r.key)).toLowerCase().includes(search.toLowerCase())).map(row=><button className={"admin-content-item "+(selected?.key===row.key?"selected":"")} key={row.key} onClick={()=>choose(row)}><b>{row.value.title||(row.value as unknown as {name:string}).name||row.key}</b><span>{section==="users"?row.key:row.value.published?"Publié":"Brouillon"}</span></button>)}
    {["media","brochures"].includes(section)&&<BulkUpload section={section} onDone={()=>open(section)} />}
    </div><div>{selected?section==="users"?<UserEditor key={selected.key+selected.revision} row={selected} onSaved={()=>open("users",true)} onDirty={setDirty} />:<DocumentEditor key={section+selected.key} section={section} row={selected} fields={section==="pages"?payload.pages?.find(p=>p.key===selected.key)?.fields||[]:payload.fields||[]} page={payload.pages?.find(p=>p.key===selected.key)?.path} onDirty={setDirty} onSaved={row=>{setDirty(false);setSelected(row);setPayload({...payload,data:[...rows.filter(r=>r.key!==row.key),row]});}} onDeleted={()=>open(section)} />:<div className="admin-card admin-empty"><h2>Choisissez un contenu</h2><p>Sélectionnez un élément dans la liste pour le modifier.</p></div>}</div></div>
   </>}
   </>}
  </main>
 </div>;
}
function RequestCard({row,team,onSaved}:{row:Entry<CustomerRequest>;team:{id:string;name:string}[];onSaved:()=>void}){
 const d=row.value;const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{await request("/api/admin/content",{section:"requests",key:row.key,revision:row.revision,action:"save",data:Object.fromEntries(new FormData(e.currentTarget))});onSaved();}catch(e){setError((e as Error).message);setBusy(false);}}
 return <article className="admin-card"><div className="admin-row"><div><span className="admin-kicker">{d.source==="reclamation"?"Réclamation client":"Demande de cotation"}</span><h2>{d.societe}</h2><p>{d.nom} · <a href={"mailto:"+d.email}>{d.email}</a> {d.telephone&&"· "+d.telephone}</p></div><span className={"admin-badge "+d.statut}>{labels[d.statut]}</span></div><small>{new Date(d.cree_le).toLocaleString("fr-FR")}</small><h3>{d.objet}</h3><p className="admin-request-text">{d.besoin}</p><form onSubmit={submit}><fieldset disabled={busy}><div className="admin-filters"><label>Statut<select name="statut" defaultValue={d.statut}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Affecter à<select name="assigned" defaultValue={d.assigned}><option value="">Non affectée</option>{team.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div><label>Note interne<textarea name="note" rows={2} maxLength={4000} placeholder="Compte rendu de l’échange, prochaine action…" /></label><button className="admin-button">{busy?"Enregistrement…":"Enregistrer le suivi"}</button></fieldset></form>{error&&<p role="alert" className="admin-error">{error}</p>}<details><summary>Historique ({d.history.length})</summary>{d.history.map((h,i)=><p key={i}><b>{h.actor}</b> · {new Date(h.date).toLocaleString("fr-FR")}<br />{h.message}</p>)}</details></article>;
}
function DocumentEditor({section,row,fields,page,onSaved,onDeleted,onDirty}:{section:string;row:Entry<Document>;fields:Field[];page?:string;onSaved:(row:Entry<Document>)=>void;onDeleted:()=>void;onDirty:(dirty:boolean)=>void}){
 const [data,setData]=useState<ContentData>({...row.value.draft}),[title,setTitle]=useState(row.value.title),[order,setOrder]=useState(row.value.order),[filter,setFilter]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[dirty,setDirty]=useState(false);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave);},[dirty]);
 function change(key:string,value:string){setData(old=>({...old,[key]:value}));setDirty(true);onDirty(true);}
 async function act(action:string){
  if((action==="delete"||action==="unpublish")&&!confirm(action==="delete"?"Retirer ce contenu du site ?":"Retirer la version publiée ?"))return;
  setBusy(true);setError("");setMessage("");
  try{const result=await request("/api/admin/content",{section,key:row.key,revision:row.revision,title,order,data,action});setDirty(false);onDirty(false);if(action==="delete"){onDeleted();return;}onSaved(result.record);setMessage(action==="publish"?"Modifications publiées.":action==="unpublish"?"Contenu retiré du site.":"Brouillon enregistré.");}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const blocks:{title:string;text:string;image:string}[]=JSON.parse(data.__blocks||"[]");
 const preview=page||({projects:"/ingenierie/nos-realisations",media:"/mediatheque",brochures:"/mediatheque",blog:"/blog",settings:"/"} as Record<string,string>)[section];
 return <div className="admin-card admin-editor"><div className="admin-row"><h2>{row.value.title}</h2><span className="admin-badge">{dirty?"Non enregistré":row.value.published?"Version publiée":"Brouillon"}</span></div><p className="admin-info">Enregistrez votre brouillon, vérifiez l’aperçu, puis publiez.</p><div className="admin-editor-actions"><button className="admin-button secondary" disabled={busy} onClick={()=>act("save")}>Enregistrer le brouillon</button><a className={"admin-button secondary "+(dirty?"disabled":"")} aria-disabled={dirty} onClick={e=>{if(dirty)e.preventDefault();}} href={"/api/admin/preview?path="+encodeURIComponent(preview)} target="_blank" rel="noreferrer">Aperçu ↗</a><button className="admin-button" disabled={busy} onClick={()=>act("publish")}>Publier</button></div>{message&&<p role="status" className="admin-success">{message}</p>}{error&&<p role="alert" className="admin-error">{error}</p>}
 <fieldset disabled={busy}><div className="admin-filters"><label>Titre dans la liste<input value={title} onChange={e=>{setTitle(e.target.value);setDirty(true);onDirty(true);}} maxLength={200} /></label>{!["pages","settings"].includes(section)&&<label>Ordre d’affichage<input type="number" min="0" max="9999" value={order} onChange={e=>{setOrder(Number(e.target.value));setDirty(true);onDirty(true);}} /></label>}</div>
 {fields.length>15&&<label>Filtrer les champs<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Titre, texte, image…" /></label>}
 {fields.filter(f=>[f.label,data[f.key]].join(" ").toLowerCase().includes(filter.toLowerCase())).map(field=><ContentField key={field.key} field={field} value={data[field.key]??""} onChange={v=>change(field.key,v)} />)}
 {section==="pages"&&<details className="admin-blocks"><summary>Blocs supplémentaires ({blocks.length})</summary>{blocks.map((block,i)=><div className="admin-block" key={i}>{(["title","text","image"] as const).map(key=><ContentField key={key} field={{key,label:key==="title"?"Titre":key==="text"?"Texte":"Image",type:key==="text"?"long":key==="image"?"image":"text"}} value={block[key]} onChange={v=>change("__blocks",JSON.stringify(blocks.map((b,j)=>j===i?{...b,[key]:v}:b)))} />)}<button className="admin-button secondary" type="button" onClick={()=>change("__blocks",JSON.stringify(blocks.filter((_,j)=>j!==i)))}>Retirer le bloc</button></div>)}<button className="admin-button secondary" type="button" onClick={()=>change("__blocks",JSON.stringify([...blocks,{title:"",text:"",image:""}]))}>+ Ajouter un bloc</button></details>}
 </fieldset><div className="admin-danger">{!["pages","settings"].includes(section)&&<><button disabled={busy} onClick={()=>act("unpublish")}>Dépublier</button><button disabled={busy} onClick={()=>act("delete")}>Supprimer ce contenu</button></>}</div></div>;
}
function ContentField({field,value,onChange}:{field:Field;value:string;onChange:(value:string)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function upload(file?:File){
  if(!file)return;setBusy(true);setError("");
  try{if(file.size>4*1024*1024)throw new Error("Choisissez un fichier de 4 Mo maximum.");const form=new FormData();form.set("file",file);const r=await fetch("/api/admin/upload",{method:"POST",body:form});const data=await r.json();if(!r.ok)throw new Error(data.message);onChange(data.url);}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <div className="admin-field"><label>{field.label}{field.type==="long"?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} maxLength={24000} />:field.type==="mediaType"?<select value={value} onChange={e=>onChange(e.target.value)}><option value="photo">Photo</option><option value="video">Vidéo</option></select>:field.key==="blogEnabled"?<select value={value} onChange={e=>onChange(e.target.value)}><option value="non">Non</option><option value="oui">Oui</option></select>:<input value={value} onChange={e=>onChange(e.target.value)} maxLength={24000} />}</label>{["image","url"].includes(field.type||"")&&<><label className="admin-upload">{busy?"Téléversement…":"Choisir un fichier · 4 Mo max"}<input type="file" accept={field.type==="image"?"image/jpeg,image/png,image/webp":"image/jpeg,image/png,image/webp,application/pdf"} disabled={busy} onChange={e=>upload(e.target.files?.[0])} /></label>{field.type==="image"&&value&&<img className="admin-image-preview" src={value} alt="Aperçu du visuel" />}</>}{error&&<p role="alert" className="admin-error">{error}</p>}</div>;
}
function BulkUpload({section,onDone}:{section:string;onDone:()=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function upload(files:FileList|null){
 if(!files?.length||busy)return;setBusy(true);setMessage("");let count=0;
 try{for(const file of Array.from(files)){const form=new FormData();form.set("file",file);const r=await fetch("/api/admin/upload",{method:"POST",body:form});const result=await r.json();if(!r.ok)throw new Error(result.message);const title=file.name.replace(/\.[^.]+$/,"");await request("/api/admin/content",{section,key:crypto.randomUUID(),revision:0,action:"save",title,data:section==="media"?{title,type:"photo",url:result.url,image:result.url,album:"À classer",description:""}:{title,url:result.url,description:""}});count++;}onDone();}catch(e){setMessage(count+" fichier(s) enregistré(s). "+(e as Error).message);}finally{setBusy(false);}
 }
 return <div className="admin-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files);}}><b>{busy?"Import en cours…":"Glissez vos fichiers ici"}</b><p>Import multiple en brouillon</p><input aria-label="Importer plusieurs fichiers" type="file" multiple accept={section==="brochures"?"application/pdf":"image/jpeg,image/png,image/webp"} disabled={busy} onChange={e=>upload(e.target.files)} />{message&&<p role="status">{message}</p>}</div>;
}
function UserEditor({row,onSaved,onDirty}:{row:Entry<Document>;onSaved:()=>void;onDirty:(dirty:boolean)=>void}){
 const value=row.value as unknown as {email?:string;name?:string;role?:string;active?:boolean};
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await request("/api/admin/content",{section:"users",key:row.key||String(data.email).trim().toLowerCase(),revision:row.revision,action:"save",data});onDirty(false);onSaved();}catch(e){setError((e as Error).message);setBusy(false);}}
 return <form className="admin-card" onSubmit={submit} onChange={()=>onDirty(true)}><h2>{row.revision?"Modifier le compte":"Créer un compte"}</h2><fieldset disabled={busy}><label>Nom<input name="name" defaultValue={value.name||""} minLength={2} required /></label><label>E-mail<input name="email" type="email" defaultValue={value.email||""} readOnly={row.revision>0} required /></label><label>Rôle<select name="role" defaultValue={value.role||"editeur"}>{Object.entries(roleNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Compte actif<select name="active" defaultValue={value.active===false?"non":"oui"}><option value="oui">Oui</option><option value="non">Non</option></select></label><label>{row.revision?"Nouveau mot de passe (laisser vide pour conserver)":"Mot de passe"}<input type="password" name="password" minLength={12} maxLength={200} required={!row.revision} autoComplete="new-password" /></label><p className="admin-info">12 caractères minimum. Communiquez le mot de passe au collaborateur par votre canal habituel.</p><button className="admin-button">Enregistrer le compte</button></fieldset>{error&&<p className="admin-error" role="alert">{error}</p>}</form>;
}
