"use client";
import PageSections from "@/components/PageSections";
import {pageLayout} from "@/content/page-builder";

import { useEffect, useRef } from "react";
import { realisations as defaultProjects, societe as defaultCompany } from "@/content/site";
import HomeQuoteForm from "./HomeQuoteForm";
import { mountHomeInteractions } from "./homeInteractions";



/** Accueil issu de la maquette validée, avec le formulaire de cotation réel. */
export default function HomeLanding({ content = {}, realisations = defaultProjects, societe = defaultCompany }: { content?: Record<string,string>; realisations?: typeof defaultProjects; societe?: typeof defaultCompany }) {
  const t = (id: string, fallback: string) => content[id] ?? fallback;
  const enabled = new Set(pageLayout("accueil",content).sections.filter(s=>s.type==="builtin").map(s=>s.source));
  const sectionLink = (id:string,source:string,fallback:string) => enabled.has(source)?"#"+id:fallback;
const slides = [
  { title: t("f116", "L’ingénierie de l’eau"), caption: t("f117", "Ingénierie de l’eau"), description: t("f118", "Études, conception, réalisation et exploitation des ouvrages"), image: t("f119", "/images/illustrations/panorama-eau.webp"), alt: t("f120", "Installation de traitement d’eau dans un paysage ouest-africain") },
  { title: t("f121", "Les services aux industries"), caption: t("f122", "Services aux industries"), description: t("f123", "Produits formulés, optimisation des utilités et services ECOLAB"), image: t("f124", "/images/illustrations/industrie.webp"), alt: t("f125", "Technicienne ouest-africaine dans une installation industrielle") },
  { title: t("f126", "L’hygiène institutionnelle"), caption: t("f127", "Hygiène institutionnelle"), description: t("f128", "Produits, équipements de dosage et expertise technique"), image: t("f129", "/images/illustrations/hygiene.webp"), alt: t("f130", "Hygiène institutionnelle : entretien du linge dans une buanderie professionnelle") },
  { title: t("f131", "Les produits chimiques"), caption: t("f132", "Produits chimiques"), description: t("f133", "NALCO, ECOLAB, commodités, réactifs et matériel de mesure"), image: t("f134", "/maquette/images/produits.webp"), alt: t("f135", "Produits chimiques conditionnés et matériel de laboratoire") },
];

  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (root.current) return mountHomeInteractions(root.current);
  }, []);
  return <div className="home-experience" ref={root}>
  <svg className="icon-defs" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><symbol id="arrow" viewBox="0 0 24 24"><path d="M5 12h14m-6-6 6 6-6 6"/></symbol><symbol id="diagonal" viewBox="0 0 24 24"><path d="M6 18 18 6M6 6h12v12"/></symbol><symbol id="phone" viewBox="0 0 24 24"><path d="m6 3 4 5-3 3c2 3 3 4 6 6l3-3 5 4c-1 4-5 4-9 2C7 17 3 12 3 7c0-2 1-4 3-4Z"/></symbol><symbol id="close" viewBox="0 0 24 24"><path d="m6 6 12 12M6 18 18 6"/></symbol></defs></svg>
  <a className="home-skip" href="#contenu">{t("f001", "Aller au contenu")}</a>
  <header className="site-header">
    <div className="shell header-inner">
      <a className="brand" href={sectionLink("accueil","section-1","/")} aria-label="EPUREAU Côte d’Ivoire — Accueil"><img src={t("f002", "/images/logo.png")} width="560" height="162" alt={t("f003", "EPUREAU Côte d’Ivoire")} /></a>
      <nav className="desktop-nav" aria-label="Navigation principale"><a href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")}>{t("f004", "Nos métiers")}</a><a href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")} data-detail="produits">{t("f005", "Produits")}</a><a href={sectionLink("realisations","section-4","/ingenierie/nos-realisations")}>{t("f006", "Réalisations")}</a><a href="/a-propos">{t("f007", "À propos")}</a><a href="/carriere">{t("f008", "Carrière")}</a></nav>
      <a className="button header-contact" href={sectionLink("contact","section-6","/contact")}>{t("f009", "Demander une cotation")}<svg aria-hidden="true"><use href="#arrow"/></svg></a>
      <button className="menu-toggle" aria-label="Ouvrir le menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button>
    </div>
    <nav id="mobile-menu" className="mobile-nav" aria-label="Navigation mobile" hidden><a href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")}>{t("f010", "Nos métiers")}</a><a href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")} data-detail="produits">{t("f011", "Produits")}</a><a href={sectionLink("realisations","section-4","/ingenierie/nos-realisations")}>{t("f012", "Réalisations")}</a><a href="/a-propos">{t("f013", "À propos")}</a><a href="/carriere">{t("f014", "Carrière")}</a><a href={sectionLink("contact","section-6","/contact")}>{t("f015", "Demander une cotation")}</a><a href="/reclamation-client">{t("f016", "Réclamation client")}</a></nav>
  </header>

  <main id="contenu"><PageSections page="accueil" values={content}>
<section id="accueil" className="home-hero" data-hero-carousel aria-roledescription="carrousel" aria-label="Les métiers EPUREAU Côte d’Ivoire">
      <div className="hero-photo">{slides.map((slide, index) => <div key={slide.caption} className={`hero-slide${index === 0 ? " is-current" : ""}`} data-hero-slide data-caption={slide.caption} data-title={slide.title} data-description={slide.description} role="group" aria-roledescription="diapositive" aria-label={`${index + 1} sur ${slides.length}`} aria-hidden={index !== 0}><img src={slide.image} width="1672" height="941" alt={slide.alt} fetchPriority={index === 0 ? "high" : "auto"} /></div>)}</div>
      <div className="shell hero-content">
        <span className="home-eyebrow light brand-name">{societe.nom}</span>
        <h1 data-hero-title>{slides[0].title}</h1>
        <p data-hero-description>{slides[0].description}</p>
        <div className="hero-actions"><a className="button cyan" href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")}>{t("f017", "Nos métiers")}<svg aria-hidden="true"><use href="#arrow"/></svg></a><a className="text-link" href={sectionLink("realisations","section-4","/ingenierie/nos-realisations")}>{t("f018", "Voir nos réalisations")}<svg aria-hidden="true"><use href="#diagonal"/></svg></a></div>
      </div>
      <div className="hero-bottom shell"><a href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")} className="scroll-link"><span>{t("f019", "↓")}</span>{t("f020", " Découvrir EPUREAU Côte d’Ivoire")}</a><div className="carousel-controls" data-hero-controls hidden><button className="carousel-button carousel-prev" type="button" data-hero-prev aria-label="Photo précédente"><svg aria-hidden="true"><use href="#arrow"/></svg></button><div className="carousel-dots">{slides.map((slide, index) => <button key={slide.caption} className="carousel-dot" type="button" data-hero-dot aria-label={`Afficher la photo ${index + 1} : ${slide.caption}`} aria-pressed={index === 0} />)}</div><span className="carousel-count" data-hero-count aria-hidden="true">{t("f021", "01 / 04")}</span><button className="carousel-button" type="button" data-hero-rotation aria-label="Mettre le défilement en pause"><span data-pause-icon><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14M16 5v14"/></svg></span><span data-play-icon hidden><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 4 12 8-12 8Z"/></svg></span></button><button className="carousel-button" type="button" data-hero-next aria-label="Photo suivante"><svg aria-hidden="true"><use href="#arrow"/></svg></button></div><span className="carousel-announcement" data-hero-announcement role="status" aria-live="polite" aria-atomic="true"></span></div>
    </section>
<aside className="home-team" aria-label="Notre équipe"><div className="shell"><strong>{t("f022", "40+")}</strong><span>{t("f023", "collaborateurs au service de vos projets")}</span><a href="/carriere">{t("f024", "Rejoindre notre équipe ↗")}</a></div></aside>
<section id="metiers" className="section services-section">
      <div className="shell services-shell">
        <div className="section-heading reveal"><div><span className="home-eyebrow">{t("f025", "Nos métiers")}</span><h2>{t("f026", "Nos domaines")}<br />{t("f027", "d’intervention")}</h2></div></div>
        <div className="services-grid">
          <a className="service-card reveal" href={sectionLink("contact","section-6","/contact")} data-detail="ingenierie"><div className="service-photo"><img src={t("f028", "/images/illustrations/ingenierie.webp")} width="1672" height="941" alt={t("f029", "Illustration : ingénieurs ouest-africains sur une installation de traitement")} loading="lazy" /></div><div className="service-body"><span className="service-topline">{t("f030", "01 ")}<svg aria-hidden="true"><use href="#diagonal"/></svg></span><h3>{t("f031", "Ingénierie")}<br />{t("f032", "de l’eau")}</h3><p>{t("f033", "Études, conception, réalisation et exploitation des ouvrages")}</p><span className="service-link">{t("f034", "Notre expertise")}</span></div></a>
          <a className="service-card reveal" href={sectionLink("contact","section-6","/contact")} data-detail="industries"><div className="service-photo"><img src={t("f035", "/images/illustrations/industrie.webp")} width="1672" height="941" alt={t("f036", "Illustration : technicienne ouest-africaine dans une installation industrielle")} loading="lazy" /></div><div className="service-body"><span className="service-topline">{t("f037", "02 ")}<svg aria-hidden="true"><use href="#diagonal"/></svg></span><h3>{t("f038", "Services")}<br />{t("f039", "aux industries")}</h3><p>{t("f040", "Produits formulés, optimisation des utilités et services ECOLAB")}</p><span className="service-link">{t("f041", "Nos services")}</span></div></a>
          <a className="service-card reveal" href={sectionLink("contact","section-6","/contact")} data-detail="hygiene"><div className="service-photo"><img src={t("f042", "/images/illustrations/hygiene.webp")} width="1672" height="941" alt={t("f043", "Illustration : entretien du linge dans une buanderie professionnelle ouest-africaine")} loading="lazy" /></div><div className="service-body"><span className="service-topline">{t("f044", "03 ")}<svg aria-hidden="true"><use href="#diagonal"/></svg></span><h3>{t("f045", "Hygiène")}<br />{t("f046", "institutionnelle")}</h3><p>{t("f047", "Produits, équipements de dosage et expertise technique")}</p><span className="service-link">{t("f048", "Nos solutions")}</span></div></a>
          <a className="service-card reveal" href={sectionLink("contact","section-6","/contact")} data-detail="produits"><div className="service-photo"><img src={t("f049", "/maquette/images/produits.webp")} width="1672" height="941" alt={t("f050", "Illustration : produits chimiques conditionnés et matériel de laboratoire")} loading="lazy" /></div><div className="service-body"><span className="service-topline">{t("f051", "04 ")}<svg aria-hidden="true"><use href="#diagonal"/></svg></span><h3>{t("f052", "Produits")}<br />{t("f053", "chimiques")}</h3><p>{t("f054", "NALCO, ECOLAB, commodités, réactifs et matériel de mesure")}</p><span className="service-link">{t("f055", "Nos produits")}</span></div></a>
        </div>
      </div>
    </section>
<section id="realisations" className="proof-section">
      <div className="shell section-heading reveal"><div><span className="home-eyebrow light">{t("f056", "Sur le terrain · Côte d’Ivoire")}</span><h2>{t("f057", "Nos réalisations")}</h2></div><a href="/ingenierie/nos-realisations" className="text-link">{t("f058", "Toutes nos réalisations")}<svg aria-hidden="true"><use href="#diagonal"/></svg></a></div>
      <div className="proof-story">
        <div className="proof-stage" aria-hidden="true"><div className="shell stage-inner"><div className="stage-rail"><span>01</span><div><i /></div><span>{String(Math.min(2,realisations.length)).padStart(2,"0")}</span></div><div className="stage-images">{realisations.slice(0,2).map((project,index)=><img key={project.slug} className={index===0?"active":""} data-case-image={index} src={project.image} alt="" width="640" height="245" loading="eager" />)}</div><span className="stage-caption">Photographies de réalisations</span></div></div>
        <div className="shell case-list">
          {realisations.slice(0,2).map((project,index)=><article className={`case-card${index===0?" active":""}`} data-case={index} key={project.slug} aria-labelledby={`project-${project.slug}`}>
            <img className="case-mobile-photo" src={project.image} alt={`Installation de traitement des eaux — ${project.nom}`} width="640" height="245" loading="lazy" />
            <span className="case-number">{String(index+1).padStart(2,"0")} / {String(realisations.length).padStart(2,"0")}</span><span className="home-eyebrow light">{project.type}</span><h3 id={`project-${project.slug}`}>{project.nom}</h3><p>{project.texte}</p><div className="case-tags"><span>{project.client}</span><span>{project.debit} {project.unite}</span></div><a className="text-link" href={`/ingenierie/nos-realisations#${project.slug}`}>{t("f061", "Voir le projet")}<svg aria-hidden="true"><use href="#diagonal" /></svg></a>
          </article>)}
        </div>
      </div>
<div className="shell catalogue-grid">{realisations.slice(2).map((project,index)=><article className="catalogue-card reveal" key={project.slug}><div className="catalogue-photo"><img src={project.image} width="640" height="245" alt={"Réalisation "+project.nom} loading="lazy" /></div><div className="catalogue-body"><span className="case-number">{String(index+3).padStart(2,"0")} / {String(realisations.length).padStart(2,"0")}</span><h3>{project.nom}</h3><span className="catalogue-location">{project.type}</span><p>{project.texte}</p><a className="text-link" href={"/ingenierie/nos-realisations#"+project.slug}>Voir le projet<svg aria-hidden="true"><use href="#diagonal" /></svg></a></div></article>)}</div>
    </section>
<section className="section references-section">
      <div className="shell references-grid">
        <div className="clients-block reveal" data-logo-carousel role="region" aria-roledescription="carrousel" aria-label="Références clients"><span className="home-eyebrow">{t("f083", "Nos références")}</span><h2>{t("f084", "Ils nous font confiance.")}</h2><div className="client-logos" id="client-logo-track" data-logo-rail tabIndex={0} role="group" aria-label="Logos des clients ; faites défiler avec les flèches"><button className="company-logo" type="button" aria-label="CARGILL" aria-pressed="false"><img src={t("f085", "/maquette/images/logos/cargill.png")} width="960" height="430" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f086", "CARGILL")}</span></button><button className="company-logo" type="button" aria-label="EUROLAIT" aria-pressed="false"><img src={t("f087", "/maquette/images/logos/eurolait.png")} width="264" height="60" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f088", "EUROLAIT")}</span></button><button className="company-logo" type="button" aria-label="BRASSIVOIRE" aria-pressed="false"><img src={t("f089", "/maquette/images/logos/brassivoire.png")} width="491" height="185" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f090", "BRASSIVOIRE")}</span></button><button className="company-logo" type="button" aria-label="Nestlé" aria-pressed="false"><img src={t("f091", "/maquette/images/logos/nestle.png")} width="221" height="228" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f092", "Nestlé")}</span></button><button className="company-logo" type="button" aria-label="PALMCI" aria-pressed="false"><img src={t("f093", "/maquette/images/logos/palmci.png")} width="100" height="100" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f094", "PALMCI")}</span></button><button className="company-logo" type="button" aria-label="PISAM" aria-pressed="false"><img src={t("f095", "/maquette/images/logos/pisam.png")} width="1475" height="579" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f096", "PISAM")}</span></button></div><div className="logo-carousel-controls" data-logo-controls hidden><button className="carousel-button carousel-prev" type="button" data-logo-prev aria-label="Logos précédents" aria-controls="client-logo-track"><svg aria-hidden="true"><use href="#arrow"/></svg></button><button className="carousel-button" type="button" data-logo-rotation aria-label="Mettre le défilement des logos en pause"><span data-pause-icon><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14M16 5v14"/></svg></span><span data-play-icon hidden><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 4 12 8-12 8Z"/></svg></span></button><button className="carousel-button" type="button" data-logo-next aria-label="Logos suivants" aria-controls="client-logo-track"><svg aria-hidden="true"><use href="#arrow"/></svg></button></div></div>
        <div className="brands-block reveal"><span className="home-eyebrow">{t("f097", "Marques représentées")}</span><div className="brand-logos"><button className="company-logo" type="button" aria-label="NALCO WATER" aria-pressed="false"><img src={t("f098", "/maquette/images/logos/nalco-water.svg")} width="233" height="49" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f099", "NALCO WATER")}</span></button><button className="company-logo" type="button" aria-label="ECOLAB" aria-pressed="false"><img src={t("f100", "/maquette/images/logos/ecolab.webp")} width="600" height="114" alt="" loading="lazy" /><span className="company-name" aria-hidden="true">{t("f101", "ECOLAB")}</span></button></div><p>{t("f102", "Traitement de l’eau")}<br />{t("f103", "Hygiène et sécurité alimentaire")}</p><a href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")} data-detail="produits" className="text-link dark">{t("f104", "Voir les produits")}<svg aria-hidden="true"><use href="#arrow"/></svg></a></div>
      </div>
    </section>
<section id="contact" className="contact-section section">
      <div className="shell contact-grid">
        <div className="contact-copy reveal"><span className="home-eyebrow">{t("f105", "Contact")}</span><h2>{t("f106", "Demander")}<br />{t("f107", "une cotation")}</h2><p>{t("f108", "Notre équipe vous accompagne.")}</p><a className="phone-link" href="tel:+2252722228905"><svg aria-hidden="true"><use href="#phone"/></svg>{t("f109", "+225 27 22 22 89 05")}</a><a className="email-link" href="mailto:epureau@epureau-ci.com">{t("f110", "epureau@epureau-ci.com")}</a><div className="contact-address">{t("f111", "Cocody, Abidjan · Côte d’Ivoire")}<br />{t("f112", "Lundi – Vendredi · 08h30 – 17h30")}</div></div>
        <HomeQuoteForm />
      </div>
    </section>
</PageSections></main>

  <dialog id="service-dialog"><button className="dialog-close" aria-label="Fermer"><svg aria-hidden="true"><use href="#close"/></svg></button><span className="home-eyebrow">{t("f113", "Nos métiers")}</span><h2 id="dialog-title"></h2><p id="dialog-description"></p><div id="dialog-points"></div><a className="button" id="dialog-contact" href={sectionLink("contact","section-6","/contact")}>{t("f114", "Contacter notre équipe")}<svg aria-hidden="true"><use href="#arrow"/></svg></a><a className="dialog-page" id="dialog-page" href={sectionLink("metiers","section-3","/ingenierie/notre-expertise")}>{t("f115", "Consulter la page métier ↗")}</a></dialog>
</div>;
}
