"use client";
import {useState} from "react";
import {blockNames,emptyBlock,pageLayout,sectionCatalog,type BlockType,type BuilderBlock,type BuilderSection,type PageLayout} from "@/content/page-builder";
import {BuilderSectionView} from "./PageSections";
import ContentField from "./AdminContentField";
type Field={key:string;label:string;type?:string};
export default function PageBuilder({page,data,fields,onChange}:{page:string;data:Record<string,string>;fields:Field[];onChange:(key:string,value:string)=>void}){
 const layout=pageLayout(page,data),catalog=sectionCatalog[page]||[];
 const [selected,setSelected]=useState(layout.sections[0]?.id||""),[kind,setKind]=useState<BlockType>("text"),[dragged,setDragged]=useState<string|null>(null),[undo,setUndo]=useState<PageLayout|null>(null),[notice,setNotice]=useState("");
 const active=layout.sections.find(s=>s.id===selected);
 const name=(s:BuilderSection)=>s.type==="builtin"?catalog.find(c=>c.id===s.source)?.label||"Section d’origine":s.title||blockNames[s.type];
 function save(sections:BuilderSection[],message="Composition modifiée"){setUndo(layout);onChange("__layout",JSON.stringify({version:1,sections}));setNotice(message);}
 function move(id:string,to:number){const from=layout.sections.findIndex(s=>s.id===id);if(from<0||to<0||to>=layout.sections.length||from===to)return;const next=[...layout.sections];const [item]=next.splice(from,1);next.splice(to,0,item);save(next,`${name(item)} déplacé à la position ${to+1}`);}
 function add(){if(layout.sections.length>=40)return;const item=emptyBlock(kind,crypto.randomUUID());save([...layout.sections,item],"Section ajoutée");setSelected(item.id);}
 function patch(part:Partial<BuilderBlock>){if(!active||active.type==="builtin")return;save(layout.sections.map(s=>s.id===active.id?{...active,...part}:s));}
 const available=catalog.filter(c=>!layout.sections.some(s=>s.type==="builtin"&&s.source===c.id));
 return <div className="page-builder">
  <div className="builder-admin-intro"><h3>Composition de la page</h3><p>Déplacez les sections par leur poignée ou avec les flèches. Sélectionnez une section pour modifier son contenu.</p></div>
  <div className="builder-add"><label>Nouvelle section<select value={kind} onChange={e=>setKind(e.target.value as BlockType)}>{Object.entries(blockNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button type="button" className="admin-button" disabled={layout.sections.length>=40} onClick={add}>+ Ajouter</button></div>
  {available.length>0&&<label>Réinsérer une section d’origine<select value="" onChange={e=>{const source=e.target.value;if(!source)return;save([...layout.sections,{id:source,type:"builtin",source}],"Section d’origine réinsérée");setSelected(source);}} disabled={layout.sections.length>=40}><option value="">Choisir une section…</option>{available.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>}
  <div className="builder-workspace"><ol className="builder-outline" aria-label="Ordre des sections">{layout.sections.map((s,i)=><li key={s.id} className={s.id===selected?"selected":""} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="move";}} onDrop={e=>{e.preventDefault();if(dragged)move(dragged,i);setDragged(null);}}>
   <span className="builder-handle" draggable onDragStart={e=>{setDragged(s.id);e.dataTransfer.setData("text/plain",s.id);e.dataTransfer.effectAllowed="move";}} onDragEnd={()=>setDragged(null)} aria-hidden="true">⠿</span>
   <button type="button" className="builder-section-select" aria-pressed={s.id===selected} onClick={()=>setSelected(s.id)}><small>{String(i+1).padStart(2,"0")} · {s.type==="builtin"?"Section d’origine":blockNames[s.type]}</small><strong>{name(s)}</strong></button>
   <div className="builder-order"><button type="button" aria-label={`Monter ${name(s)}`} disabled={i===0} onClick={()=>move(s.id,i-1)}>↑</button><button type="button" aria-label={`Descendre ${name(s)}`} disabled={i===layout.sections.length-1} onClick={()=>move(s.id,i+1)}>↓</button></div>
  </li>)}</ol>
  <div className="builder-properties">{active?<><div className="admin-row"><h3>{name(active)}</h3><button type="button" className="builder-remove" onClick={()=>{save(layout.sections.filter(s=>s.id!==active.id),"Section retirée du brouillon");setSelected("");}}>Retirer la section</button></div>
   {active.type==="builtin"?<><p className="admin-info">La présentation et les animations d’origine sont conservées.</p>{fields.filter(f=>catalog.find(c=>c.id===active.source)?.fields.includes(f.key)).map(f=><ContentField key={f.key} field={f} value={data[f.key]||""} onChange={v=>onChange(f.key,v)} />)}<p>Les réalisations, médias et paramètres partagés se modifient dans leurs rubriques respectives.</p></>:<>
    <label>Fond de section<select value={active.theme} onChange={e=>patch({theme:e.target.value as BuilderBlock["theme"]})}><option value="light">Blanc</option><option value="soft">Bleu clair</option><option value="dark">Bleu foncé</option></select></label>
    {([{key:"title",label:"Titre de la section"},{key:"text",label:"Texte",type:"long"},{key:"image",label:"Image principale",type:"image"},{key:"alt",label:"Description de l’image"},{key:"href",label:"Destination du bouton"},{key:"buttonLabel",label:"Texte du bouton"}] as Field[]).map(f=><ContentField key={f.key} field={f} value={String(active[f.key as keyof BuilderBlock]||"")} onChange={v=>patch({[f.key]:v})} />)}
    {["cards","gallery","carousel","faq"].includes(active.type)&&<div className="builder-item-editor"><h4>{active.type==="carousel"?"Diapositives":active.type==="faq"?"Questions et réponses":"Éléments"}</h4>{active.items.map((item,i)=><details key={item.id} open><summary>{i+1}. {item.title||"Nouvel élément"}</summary>{([{key:"title",label:active.type==="faq"?"Question":"Titre"},{key:"text",label:active.type==="faq"?"Réponse":"Texte",type:"long"},...(active.type==="faq"?[]:[{key:"image",label:"Image",type:"image"},{key:"alt",label:"Description de l’image"},{key:"href",label:"Lien"}])] as Field[]).map(f=><ContentField key={f.key} field={f} value={item[f.key as keyof typeof item]} onChange={v=>patch({items:active.items.map(x=>x.id===item.id?{...x,[f.key]:v}:x)})} />)}<div className="builder-item-actions"><button type="button" disabled={i===0} onClick={()=>{const items=[...active.items];[items[i-1],items[i]]=[items[i],items[i-1]];patch({items});}}>Monter</button><button type="button" disabled={i===active.items.length-1} onClick={()=>{const items=[...active.items];[items[i+1],items[i]]=[items[i],items[i+1]];patch({items});}}>Descendre</button><button type="button" onClick={()=>patch({items:active.items.filter(x=>x.id!==item.id)})}>Retirer cet élément</button></div></details>)}<button type="button" className="admin-button secondary" disabled={active.items.length>=20} onClick={()=>patch({items:[...active.items,{id:crypto.randomUUID(),title:"",text:"",image:"",alt:"",href:""}]})}>+ Ajouter {active.type==="carousel"?"une diapositive":active.type==="faq"?"une question":"un élément"}</button></div>}
    <details className="builder-preview"><summary>Aperçu de cette section</summary><BuilderSectionView block={active} /></details>
   </>}
  </>:<p className="admin-empty">Ajoutez ou sélectionnez une section.</p>}</div></div>
  <div className="builder-status"><span role="status">{notice||`${layout.sections.length} section(s)`}</span>{undo&&<button type="button" onClick={()=>{onChange("__layout",JSON.stringify(undo));setUndo(null);setNotice("Dernière modification annulée");}}>Annuler la dernière modification</button>}</div>
  {fields.length>0&&<details className="builder-all-fields"><summary>Tous les textes et images de la page</summary>{fields.map(f=><ContentField key={f.key} field={f} value={data[f.key]||""} onChange={v=>onChange(f.key,v)} />)}</details>}
 </div>;
}
